version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      development-tooling:
        patterns:
          - "mypy"
          - "ruff"
          - "codespell"
          - "coverage"
          - "pandas"
          - "defusedxml"
          - "bandit"
          - "pip-audit"
